/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_fileselection1 (void);
GtkWidget* create_window_cell_properties (void);
GtkWidget* create_window_courant_properties (void);
GtkWidget* create_window_brush_configure (void);
GtkWidget* create_fileselection2 (void);
GtkWidget* create_fileselection_export_elcom (void);
GtkWidget* create_window_map_properties (void);
